spring:
  application:
    name: spring-cloud-admin
  zipkin:
    base-url: http://localhost:8768

server:
  port: 8769

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
