spring:
  application:
    name: spring-cloud-consumer
  zipkin:
      base-url: http://localhost:8768

server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
