spring:
  application:
    name: spring-cloud-config-client
  cloud:
    config:
      uri: http://localhost:8766
      name: config-client
      label: master
      profile: dev
  zipkin:
    base-url: http://localhost:8768

server:
  port: 8767

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
