spring:
  application:
    name: spring-cloud-zuul
  zipkin:
    base-url: http://localhost:8768

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: spring-cloud-provider
    api-b:
      path: /api/b/**
      serviceId: spring-cloud-consumer
