spring:
  application:
    name: spring-cloud-admin-client
  boot:
    admin:
      client:
        url: http://localhost:8769
  zipkin:
    base-url: http://localhost:8768

server:
  port: 8770

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
