spring:
  application:
    name: spring-cloud-zipkin
  main:
    allow-bean-definition-overriding: true

server:
  port: 8768

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
